version: '3.1'
services:
  onlybot_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Boubout0!"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  # onlybot_api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_API
  #   ports:
  #     - "44320:80"
  #     - "44321:443"
  #   environment:
  #     ASPNETCORE_URLS: "https://+:443;http://+:80"
  #     ASPNETCORE_HTTPS_PORT: "44321"
  #     ASPNETCORE_ENVIRONMENT: "Development"
  #   volumes:
  #     - ${APPDATA}/microsoft/UserSecrets:/root/.microsoft/usersecrets
  #     - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
  # onlybot_server:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile_Server
  #   ports:
  #     - "44330:80"
  #     - "44331:443"
  #   environment:
  #     ASPNETCORE_URLS: "https://+:443;http://+:80"
  #     ASPNETCORE_HTTPS_PORT: "44331"
  #     ASPNETCORE_ENVIRONMENT: "Development"
  #   volumes:
  #     - ${APPDATA}/microsoft/UserSecrets:/root/.microsoft/usersecrets
  #     - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https