version: '4.32'
services:
  onlybot_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Boubout0!"
      MSSQL_PID: Express
    networks:
      - onlybot_network
    ports:
      - "1433:1433"

  onlybot_api:
    build:
      context: .
      dockerfile: OnlyBot_API/Dockerfile
    networks:
      - onlybot_network
    ports:
      - "44320:80"
      - "44321:443"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "44321"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/root/.aspnet/https/OnlyBot_API.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Boubout0!"
    volumes:
      - ${APPDATA}/microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https
    depends_on:
      - onlybot_db


networks:
  onlybot_network:
    driver: bridge
